version: '3.8'

services:
  db:
    image: postgres:16
    container_name: organizacard-postgres-db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - organizacard-data:/var/lib/postgresql/data
    networks:
      - organizacard-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s        
      timeout: 5s          
      retries: 5           
      start_period: 10s     

networks:
  organizacard-network:
    driver: bridge

volumes:
  organizacard-data:
    driver: local
    driver_opts:
      type: none
      device: "D:/docker/postgres-data"
      o: bind